name: Build Releases

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabihf
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - mips-unknown-linux-gnu
          - mips-unknown-linux-musl
          - mipsel-unknown-linux-gnu
          - mipsel-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: taiki-e/install-action@cross
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cross build --release --target ${{ matrix.target }}
      - name: Compress
        run: |
          cd target/${{ matrix.target }}/release
          zip tonel_${{ matrix.target }}.zip tonelc tonels
      - name: Upload GitHub Assets
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/*.zip
          prerelease: ${{ contains(github.ref, '-') }}

  build-macos:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Compress
        run: |
          cd target/${{ matrix.target }}/release
          zip tonel_${{ matrix.target }}.zip tonelc tonels
      - name: Upload GitHub Assets
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/*.zip
          prerelease: ${{ contains(github.ref, '-') }}
